# Generated by Django 4.2.5 on 2023-09-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('mobileNo', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('profilePic', models.FileField(null=True, upload_to='')),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pin', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
