# Generated by Django 4.2.5 on 2023-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0002_user_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=10, null=True)),
                ('a_name', models.CharField(max_length=200, null=True)),
                ('a_email', models.CharField(max_length=30, null=True)),
                ('a_mobileNo', models.CharField(max_length=15, null=True)),
                ('a_alterNo', models.CharField(max_length=15, null=True)),
                ('a_address', models.TextField(null=True)),
                ('a_identity', models.FileField(null=True, upload_to='')),
                ('a_remark', models.CharField(max_length=400, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
