# Generated by Django 3.2.12 on 2023-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0006_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
