# Generated by Django 3.2.12 on 2023-11-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0008_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
