# Generated by Django 3.2.12 on 2023-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0009_alter_addtocart_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='item_total',
            field=models.IntegerField(null=True),
        ),
    ]
