# Generated by Django 3.2.12 on 2023-12-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0011_addtocart_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('phn_no', models.CharField(max_length=15, null=True)),
                ('landmark', models.TextField(null=True)),
                ('town', models.TextField(null=True)),
                ('adrs_type', models.TextField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='total',
        ),
    ]
