# Generated by Django 3.2.12 on 2023-12-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0012_auto_20231205_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='town',
        ),
    ]
