# Generated by Django 3.2.12 on 2023-12-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0013_remove_payments_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('card_owner', models.CharField(max_length=30, null=True)),
                ('total_amt', models.IntegerField(null=True)),
                ('card_no', models.IntegerField(null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='payments',
            name='adrs_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
