# Generated by Django 3.2.12 on 2023-12-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0014_auto_20231211_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('user_img', models.FileField(null=True, upload_to='')),
                ('email', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('name_artist', models.CharField(max_length=30, null=True)),
                ('quality', models.CharField(max_length=30, null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
    ]
