# Generated by Django 3.2.12 on 2024-01-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0016_artwork_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
