# Generated by Django 3.2.12 on 2024-01-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0018_addtocart_artist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('artist_name', models.CharField(max_length=200, null=True)),
                ('item_id', models.IntegerField(null=True)),
                ('item', models.CharField(max_length=30, null=True)),
                ('qnty', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('p_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMode',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='total',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='add_status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
