# Generated by Django 3.2.12 on 2024-01-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0019_auto_20240105_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='p_status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
