# Generated by Django 3.2.12 on 2024-01-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0020_payments_p_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='adrs_type',
        ),
    ]
