# Generated by Django 3.2.12 on 2024-01-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0021_remove_payments_adrs_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_order',
            old_name='artist_name',
            new_name='ar_name',
        ),
        migrations.RenameField(
            model_name='my_order',
            old_name='item',
            new_name='m_item',
        ),
        migrations.RenameField(
            model_name='my_order',
            old_name='item_id',
            new_name='m_item_id',
        ),
        migrations.RenameField(
            model_name='my_order',
            old_name='qnty',
            new_name='m_qnty',
        ),
        migrations.RenameField(
            model_name='my_order',
            old_name='p_status',
            new_name='m_status',
        ),
        migrations.RenameField(
            model_name='my_order',
            old_name='total',
            new_name='m_total',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='item_image',
        ),
    ]
