# Generated by Django 3.2.12 on 2024-01-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0022_auto_20240105_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_order',
            old_name='ar_name',
            new_name='name',
        ),
    ]
