# Generated by Django 3.2.12 on 2024-01-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artco', '0023_rename_ar_name_my_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Recieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, null=True)),
                ('o_name', models.CharField(max_length=200, null=True)),
                ('o_item_id', models.IntegerField(null=True)),
                ('o_item', models.CharField(max_length=30, null=True)),
                ('o_qnty', models.IntegerField(null=True)),
                ('o_total', models.IntegerField(null=True)),
                ('o_status', models.CharField(max_length=15)),
            ],
        ),
    ]
